{% set name = "img2pdf" %}
{% set version = "0.3.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8cd5509a60b75f4442b897bad3d593e25ebd314105f3034a8f17def396a4a0fb

build:
  number: 1
  skip: true  # [python_impl == 'pypy']
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - img2pdf = img2pdf:main

requirements:
  host:
    - python
    - pip
  run:
    - python
    - pillow
    - enum34  # [py<34]

test:
  imports:
    - img2pdf
  commands:
    - img2pdf --help

about:
  home: https://gitlab.mister-muffin.de/josch/img2pdf
  license: LGPL-3.0
  license_family: LGPL
  license_file: LICENSE
  summary: 'Lossless conversion of raster images to PDF'
  description: |
    Lossless conversion of raster images to PDF. You should use img2pdf if your priorities
    are (in this order):

    1. always lossless: the image embedded in the PDF will always have the exact same color information for every pixel as the input
    2. small: if possible, the difference in filesize between the input image and the output PDF will only be the overhead of the PDF container itself
    3 fast: if possible, the input image is just pasted into the PDF document as-is without any CPU hungry re-encoding of the pixel data

extra:
  recipe-maintainers:
    - dougalsutherland
