{% set name = "img2pdf" %}
{% set version = "0.4.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8ec898a9646523fd3862b154f3f47cd52609c24cc3e2dc1fb5f0168f0cbe793c

build:
  number: 1
  skip: true  # [python_impl == 'pypy']
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - img2pdf = img2pdf:main

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
  run:
    - python
    - pillow
    - enum34  # [py<34]

test:
  imports:
    - img2pdf
  commands:
    - img2pdf --help

about:
  home: https://gitlab.mister-muffin.de/josch/img2pdf
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE
  summary: Lossless conversion of raster images to PDF
  description: |
    Lossless conversion of raster images to PDF. You should use img2pdf if your priorities
    are (in this order):

    1. always lossless: the image embedded in the PDF will always have the exact same color information for every pixel as the input
    2. small: if possible, the difference in filesize between the input image and the output PDF will only be the overhead of the PDF container itself
    3 fast: if possible, the input image is just pasted into the PDF document as-is without any CPU hungry re-encoding of the pixel data

extra:
  recipe-maintainers:
    - jonashaag
    - izahn
    - djsutherland
